<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $datos = [
            [
                'name' => 'Café Caramel con Chocolate',
                'slug' => Str::slug('Café Caramel con Chocolate'),
                'price' => 59.9,
                'image' => 'cafe_01',
                'category_id' => 1,
                'available' => true,
            ],
            [
                'name' => 'Café Frio con Chocolate Grande',
                'slug' => Str::slug('Café Frio con Chocolate Grande'),
                'price' => 49.9,
                'image' => 'cafe_02',
                'category_id' => 1,
                'available' => true,
            ],
            [
                'name' => 'Latte Frio con Chocolate Grande',
                'slug' => Str::slug('Latte Frio con Chocolate Grande'),
                'price' => 54.9,
                'image' => 'cafe_03',
                'category_id' => 1,
                'available' => true,
            ],
            [
                'name' => 'Malteada Fria con Chocolate Grande',
                'slug' => Str::slug('Malteada Fria con Chocolate Grande'),
                'price' => 54.9,
                'image' => 'cafe_05',
                'category_id' => 1,
                'available' => true,
            ],
            [
                'name' => 'Café Mocha Caliente Chico',
                'slug' => Str::slug('Café Mocha Caliente Chico'),
                'price' => 39.9,
                'image' => 'cafe_06',
                'category_id' => 1,
                'available' => true,
            ],
            [
                'name' => 'Café Mocha Caliente Grande con Chocolate',
                'slug' => Str::slug('Café Mocha Caliente Grande con Chocolate'),
                'price' => 59.9,
                'image' => 'cafe_07',
                'category_id' => 1,
                'available' => true,
            ],
            [
                'name' => 'Café Caliente Capuchino Grande',
                'slug' => Str::slug('Café Caliente Capuchino Grande'),
                'price' => 59.9,
                'image' => 'cafe_08',
                'category_id' => 1,
                'available' => true,
            ],
            [
                'name' => 'Café Mocha Caliente Mediano',
                'slug' => Str::slug('Café Mocha Caliente Mediano'),
                'price' => 49.9,
                'image' => 'cafe_09',
                'category_id' => 1,
                'available' => true,
            ],
            [
                'name' => 'Café Mocha Frio con Caramelo Mediano',
                'slug' => Str::slug('Café Mocha Frio con Caramelo Mediano'),
                'price' => 49.9,
                'image' => 'cafe_10',
                'category_id' => 1,
                'available' => true,
            ],
            [
                'name' => 'Café Mocha Frio con Chocolate Mediano',
                'slug' => Str::slug('Café Mocha Frio con Chocolate Mediano'),
                'price' => 49.9,
                'image' => 'cafe_11',
                'category_id' => 1,
                'available' => true,
            ],
            [
                'name' => 'Café Espresso',
                'slug' => Str::slug('Café Espresso'),
                'price' => 29.9,
                'image' => 'cafe_12',
                'category_id' => 1,
                'available' => true,
            ],
            [
                'name' => 'Café Capuchino Grande con Caramelo',
                'slug' => Str::slug('Café Capuchino Grande con Caramelo'),
                'price' => 59.9,
                'image' => 'cafe_13',
                'category_id' => 1,
                'available' => true,
            ],
            [
                'name' => 'Café Caramelo Grande',
                'slug' => Str::slug('Café Caramelo Grande'),
                'price' => 59.9,
                'image' => 'cafe_14',
                'category_id' => 1,
                'available' => true,
            ],
            [
                'name' => 'Paquete de 3 donas de Chocolate',
                'slug' => Str::slug('Paquete de 3 donas de Chocolate'),
                'price' => 39.9,
                'image' => 'donas_01',
                'category_id' => 4,
                'available' => true,
            ],
            [
                'name' => 'Paquete de 3 donas Glaseadas',
                'slug' => Str::slug('Paquete de 3 donas Glaseadas'),
                'price' => 39.9,
                'image' => 'donas_02',
                'category_id' => 4,
                'available' => true,
            ],
            [
                'name' => 'Dona de Fresa',
                'slug' => Str::slug('Dona de Fresa'),
                'price' => 19.9,
                'image' => 'donas_03',
                'category_id' => 4,
                'available' => true,
            ],
            [
                'name' => 'Dona con Galleta de Chocolate',
                'slug' => Str::slug('Dona con Galleta de Chocolate'),
                'price' => 19.9,
                'image' => 'donas_04',
                'category_id' => 4,
                'available' => true,
            ],
            [
                'name' => 'Dona glass con Chispas Sabor Fresa',
                'slug' => Str::slug('Dona glass con Chispas Sabor Fresa'),
                'price' => 19.9,
                'image' => 'donas_05',
                'category_id' => 4,
                'available' => true,
            ],
            [
                'name' => 'Dona glass con Chocolate',
                'slug' => Str::slug('Dona glass con Chocolate'),
                'price' => 19.9,
                'image' => 'donas_06',
                'category_id' => 4,
                'available' => true,
            ],
            [
                'name' => 'Dona de Chocolate con MÁS Chocolate',
                'slug' => Str::slug('Dona de Chocolate con MÁS Chocolate'),
                'price' => 19.9,
                'image' => 'donas_07',
                'category_id' => 4,
                'available' => true,
            ],
            [
                'name' => 'Paquete de 3 donas con Vainilla y Chocolate',
                'slug' => Str::slug('Paquete de 3 donas con Vainilla y Chocolate'),
                'price' => 39.9,
                'image' => 'donas_09',
                'category_id' => 4,
                'available' => true,
            ],
            [
                'name' => 'Paquete de 6 Donas',
                'slug' => Str::slug('Paquete de 6 Donas'),
                'price' => 69.9,
                'image' => 'donas_10',
                'category_id' => 4,
                'available' => true,
            ],
            [
                'name' => 'Paquete de 3 Variadas',
                'slug' => Str::slug('Paquete de 3 Variadas'),
                'price' => 39.9,
                'image' => 'donas_11',
                'category_id' => 4,
                'available' => true,
            ],
            [
                'name' => 'Dona Natural con Chocolate',
                'slug' => Str::slug('Dona Natural con Chocolate'),
                'price' => 19.9,
                'image' => 'donas_12',
                'category_id' => 4,
                'available' => true,
            ],
            [
                'name' => 'Paquete de 3 Donas de Chocolate con Chispas',
                'slug' => Str::slug('Paquete de 3 Donas de Chocolate con Chispas'),
                'price' => 39.9,
                'image' => 'donas_13',
                'category_id' => 4,
                'available' => true,
            ],
            [
                'name' => 'Dona Chocolate y Coco',
                'slug' => Str::slug('Dona Chocolate y Coco'),
                'price' => 19.9,
                'image' => 'donas_14',
                'category_id' => 4,
                'available' => true,
            ],
            [
                'name' => 'Paquete Galletas de Chocolate',
                'slug' => Str::slug('Paquete Galletas de Chocolate'),
                'price' => 29.9,
                'image' => 'galletas_01',
                'category_id' => 6,
                'available' => true,
            ],
            [
                'name' => 'Paquete Galletas de Chocolate y Avena',
                'slug' => Str::slug('Paquete Galletas de Chocolate y Avena'),
                'price' => 39.9,
                'image' => 'galletas_02',
                'category_id' => 6,
                'available' => true,
            ],
            [
                'name' => 'Paquete de Muffins de Vainilla',
                'slug' => Str::slug('Paquete de Muffins de Vainilla'),
                'price' => 39.9,
                'image' => 'galletas_03',
                'category_id' => 6,
                'available' => true,
            ],
            [
                'name' => 'Paquete de 4 Galletas de Avena',
                'slug' => Str::slug('Paquete de 4 Galletas de Avena'),
                'price' => 24.9,
                'image' => 'galletas_04',
                'category_id' => 6,
                'available' => true,
            ],
            [
                'name' => 'Galletas de Mantequilla Variadas',
                'slug' => Str::slug('Galletas de Mantequilla Variadas'),
                'price' => 39.9,
                'image' => 'galletas_05',
                'category_id' => 6,
                'available' => true,
            ],
            [
                'name' => 'Galletas de sabores frutales',
                'slug' => Str::slug('Galletas de sabores frutales'),
                'price' => 39.9,
                'image' => 'galletas_06',
                'category_id' => 6,
                'available' => true,
            ],
            [
                'name' => 'Hamburguesa Sencilla',
                'slug' => Str::slug('Hamburguesa Sencilla'),
                'price' => 59.9,
                'image' => 'hamburguesas_01',
                'category_id' => 2,
                'available' => true,
            ],
            [
                'name' => 'Hamburguesa de Pollo',
                'slug' => Str::slug('Hamburguesa de Pollo'),
                'price' => 59.9,
                'image' => 'hamburguesas_02',
                'category_id' => 2,
                'available' => true,
            ],
            [
                'name' => 'Hamburguesa de Pollo y Chili',
                'slug' => Str::slug('Hamburguesa de Pollo y Chili'),
                'price' => 59.9,
                'image' => 'hamburguesas_03',
                'category_id' => 2,
                'available' => true,
            ],
            [
                'name' => 'Hamburguesa Queso y Pepinos',
                'slug' => Str::slug('Hamburguesa Queso y Pepinos'),
                'price' => 59.9,
                'image' => 'hamburguesas_04',
                'category_id' => 2,
                'available' => true,
            ],
            [
                'name' => 'Hamburguesa Cuarto de Libra',
                'slug' => Str::slug('Hamburguesa Cuarto de Libra'),
                'price' => 59.9,
                'image' => 'hamburguesas_05',
                'category_id' => 2,
                'available' => true,
            ],
            [
                'name' => 'Hamburguesa Doble Queso',
                'slug' => Str::slug('Hamburguesa Doble Queso'),
                'price' => 69.9,
                'image' => 'hamburguesas_06',
                'category_id' => 2,
                'available' => true,
            ],
            [
                'name' => 'Hot Dog Especial',
                'slug' => Str::slug('Hot Dog Especial'),
                'price' => 49.9,
                'image' => 'hamburguesas_07',
                'category_id' => 2,
                'available' => true,
            ],
            [
                'name' => 'Paquete 2 Hot Dogs',
                'slug' => Str::slug('Paquete 2 Hot Dogs'),
                'price' => 69.9,
                'image' => 'hamburguesas_08',
                'category_id' => 2,
                'available' => true,
            ],
            [
                'name' => '4 Rebanadas de Pay de Queso',
                'slug' => Str::slug('4 Rebanadas de Pay de Queso'),
                'price' => 69.9,
                'image' => 'pastel_01',
                'category_id' => 5,
                'available' => true,
            ],
            [
                'name' => 'Waffle Especial',
                'slug' => Str::slug('Waffle Especial'),
                'price' => 49.9,
                'image' => 'pastel_02',
                'category_id' => 5,
                'available' => true,
            ],
            [
                'name' => 'Croissants De la casa',
                'slug' => Str::slug('Croissants De la casa'),
                'price' => 39.9,
                'image' => 'pastel_03',
                'category_id' => 5,
                'available' => true,
            ],
            [
                'name' => 'Pay de Queso',
                'slug' => Str::slug('Pay de Queso'),
                'price' => 19.9,
                'image' => 'pastel_04',
                'category_id' => 5,
                'available' => true,
            ],
            [
                'name' => 'Pastel de Chocolate',
                'slug' => Str::slug('Pastel de Chocolate'),
                'price' => 29.9,
                'image' => 'pastel_05',
                'category_id' => 5,
                'available' => true,
            ],
            [
                'name' => 'Rebanada Pastel de Chocolate',
                'slug' => Str::slug('Rebanada Pastel de Chocolate'),
                'price' => 29.9,
                'image' => 'pastel_06',
                'category_id' => 5,
                'available' => true,
            ],
            [
                'name' => 'Pizza Spicy con Doble Queso',
                'slug' => Str::slug('Pizza Spicy con Doble Queso'),
                'price' => 69.9,
                'image' => 'pizzas_01',
                'category_id' => 3,
                'available' => true,
            ],
            [
                'name' => 'Pizza Jamón y Queso',
                'slug' => Str::slug('Pizza Jamón y Queso'),
                'price' => 69.9,
                'image' => 'pizzas_02',
                'category_id' => 3,
                'available' => true,
            ],
            [
                'name' => 'Pizza Doble Queso',
                'slug' => Str::slug('Pizza Doble Queso'),
                'price' => 69.9,
                'image' => 'pizzas_03',
                'category_id' => 3,
                'available' => true,
            ],
            [
                'name' => 'Pizza Especial de la Casa',
                'slug' => Str::slug('Pizza Especial de la Casa'),
                'price' => 69.9,
                'image' => 'pizzas_04',
                'category_id' => 3,
                'available' => true,
            ],
            [
                'name' => 'Pizza Chorizo',
                'slug' => Str::slug('Pizza Chorizo'),
                'price' => 69.9,
                'image' => 'pizzas_05',
                'category_id' => 3,
                'available' => true,
            ],
            [
                'name' => 'Pizza Hawaiana',
                'slug' => Str::slug('Pizza Hawaiana'),
                'price' => 69.9,
                'image' => 'pizzas_06',
                'category_id' => 3,
                'available' => true,
            ],
            [
                'name' => 'Pizza Tocino',
                'slug' => Str::slug('Pizza Tocino'),
                'price' => 69.9,
                'image' => 'pizzas_07',
                'category_id' => 3,
                'available' => true,
            ],
            [
                'name' => 'Pizza Vegetales y Queso',
                'slug' => Str::slug('Pizza Vegetales y Queso'),
                'price' => 69.9,
                'image' => 'pizzas_08',
                'category_id' => 3,
                'available' => true,
            ],
            [
                'name' => 'Pizza Pepperoni y Queso',
                'slug' => Str::slug('Pizza Pepperoni y Queso'),
                'price' => 69.9,
                'image' => 'pizzas_09',
                'category_id' => 3,
                'available' => true,
            ],
            [
                'name' => 'Pizza Aceitunas y Queso',
                'slug' => Str::slug('Pizza Aceitunas y Queso'),
                'price' => 69.9,
                'image' => 'pizzas_10',
                'category_id' => 3,
                'available' => true,
            ],
            [
                'name' => 'Pizza Queso, Jamón y Champiñones',
                'slug' => Str::slug('Pizza Queso, Jamón y Champiñones'),
                'price' => 69.9,
                'image' => 'pizzas_11',
                'category_id' => 3,
                'available' => true,
            ],
        ];

        Product::insert($datos);
    }
}
